version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3737 -b '0.0.0.0'"
    volumes:
      - .:/danielpariente
    ports:
      - "80:3737"
    depends_on:
      - db
