
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dan

test:
  <<: *default
  database: dan_test

production:
  <<: *default
  database: dan_prod
